/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FestivalRegistry } from "./FestivalRegistry";
export type { FestivalTicket } from "./FestivalTicket";
